# Generated by Django 5.1.7 on 2025-09-03 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entretien', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='hr.joboffer'),
        ),
        migrations.AddField(
            model_name='reponseentretien',
            name='entretien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='entretien.entretien'),
        ),
    ]
