# Generated by Django 5.1.7 on 2025-09-03 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidat', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hr.joboffer'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='applied_offers',
            field=models.ManyToManyField(related_name='Candidate', through='candidat.Application', to='hr.joboffer'),
        ),
    ]
